name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      run: |
        curl -OL https://go.dev/dl/go1.18beta1.linux-amd64.tar.gz
        rm -rf /usr/local/go
        tar -C /usr/local -xzf go1.18beta1.linux-amd64.tar.gz

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
