name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOROOT: /usr/local/go
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      run: |
        curl -OL https://go.dev/dl/go1.18beta1.linux-amd64.tar.gz
        sudo rm -rf $GOROOT
        sudo tar -C /usr/local -xzf go1.18beta1.linux-amd64.tar.gz

    - name: Build
      run: $GOROOT/bin/go build -v ./...

    - name: Test
      run: $GOROOT/bin/go test -v ./...

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1
