name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      GOROOT: /usr/local/go
      GOVERSION: go1.18.linux-amd64
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      run: |
        curl -OL https://go.dev/dl/$GOVERSION.tar.gz
        sudo rm -rf $GOROOT
        sudo tar -C /usr/local -xzf $GOVERSION.tar.gz

    - name: Test
      run: make test

    - name: Upload coverage to codecov.io
      uses: codecov/codecov-action@v1

    - name: Build
      run: make build
